name: Languages
on:
  workflow_dispatch:
  schedule: [{ cron: "0 0 * * 0" }] # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate languages statistics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: dist/metrics.plugin.languages.indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_analysis_timeout: 15

      - name: Publish `dist` to `output` branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
